# Generated by Django 3.0.4 on 2020-03-19 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_auto_20200319_0228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '사용자'},
        ),
        migrations.AlterModelTable(
            name='user',
            table='signup_user',
        ),
    ]
