# Generated by Django 3.0.4 on 2020-03-26 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20200325_0934'),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'verbose_name': '게시글', 'verbose_name_plural': '게시글'},
        ),
        migrations.AddField(
            model_name='board',
            name='registered_dttm',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='등록시간'),
        ),
        migrations.AddField(
            model_name='board',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.User', verbose_name='작성자'),
        ),
        migrations.AlterModelTable(
            name='board',
            table='board',
        ),
    ]
