# Generated by Django 3.0.4 on 2020-03-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('board', '0003_board_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='tags',
            field=models.ManyToManyField(null=True, to='tag.Tag', verbose_name='태그'),
        ),
    ]
